/*
 * USER
 * ExchangerPoint Crypto Exchange Plateform - USER Specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.user;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * IpVerificationRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-01T06:52:50.420Z")
public class IpVerificationRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("verificationCode")
  private String verificationCode = null;

  public IpVerificationRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public IpVerificationRequest verificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
    return this;
  }

   /**
   *  verificationCode
   * @return verificationCode
  **/
  @ApiModelProperty(required = true, value = "VerificationCode")
  public String getVerificationCode() {
    return verificationCode;
  }

  public void setVerificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpVerificationRequest activateAccountRequest = (IpVerificationRequest) o;
    return Objects.equals(this.userName, activateAccountRequest.userName) &&
        Objects.equals(this.verificationCode, activateAccountRequest.verificationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, verificationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpVerificationRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

