/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.user;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdateUserRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-13T08:11:56.172Z")
public class UpdateUserRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("name")
  private String name = null;

  
  @SerializedName("country")
  private String country = null;

  @SerializedName("pin")
  private String pin = null;

  public UpdateUserRequest userName(String userName) {
    this.userName = userName;
    return this;
  }
  
  
  public UpdateUserRequest(String userName, String name, String country, String pin) {
	    this.userName = userName;
	    this.name = name;
	    this.country =  country;
	    this.pin = pin;
	    
	  }

   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UpdateUserRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Account owner name 
   * @return name
  **/
  @ApiModelProperty(value = "Account owner name ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  
  public UpdateUserRequest country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public UpdateUserRequest pin(String pin) {
    this.pin = pin;
    return this;
  }

   /**
   * Get pin
   * @return pin
  **/
  @ApiModelProperty(value = "")
  public String getPin() {
    return pin;
  }

  public void setPin(String pin) {
    this.pin = pin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserRequest updateUserRequest = (UpdateUserRequest) o;
    return Objects.equals(this.userName, updateUserRequest.userName) &&
        Objects.equals(this.name, updateUserRequest.name) &&
        Objects.equals(this.country, updateUserRequest.country) &&
        Objects.equals(this.pin, updateUserRequest.pin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, name, country, pin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


public UpdateUserRequest() {
	
}

}

