/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.user;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdatePhoneRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-13T07:27:42.774Z")
public class UpdatePhoneRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("phone")
  private String phone = null;
  
  @SerializedName("pin")
  private String pin = null;
  
  @SerializedName("verificationCode")
  private String verificationCode = null;


  public UpdatePhoneRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }
  
  public UpdatePhoneRequest verificationCode(String verificationCode) {
	    this.verificationCode = verificationCode;
	    return this;
	  }

	   /**
	   * User verificationCodee
	   * @return verificationCode
	  **/
	  @ApiModelProperty(required = true, value = "phone verification Code")
	  public String getVerificationCode() {
	    return verificationCode;
	  }

	  public void setVerificationCode(String verificationCode) {
	    this.verificationCode = verificationCode;
	  }


  public UpdatePhoneRequest phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * User new phone
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "User new phone")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public UpdatePhoneRequest pin(String pin) {
	    this.pin = pin;
	    return this;
	  }

	   /**
	   * User pin
	   * @return pin
	  **/
	  @ApiModelProperty(required = true, value = "User pin")
	  public String getPin() {
	    return pin;
	  }

	  public void setPin(String pin) {
	    this.pin = pin;
	  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePhoneRequest updatePhoneRequest = (UpdatePhoneRequest) o;
    return Objects.equals(this.userName, updatePhoneRequest.userName) &&
    		Objects.equals(this.verificationCode, updatePhoneRequest.verificationCode) &&
    		Objects.equals(this.pin, updatePhoneRequest.pin) &&
        Objects.equals(this.phone, updatePhoneRequest.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, phone, pin, verificationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePhoneRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

