/*
 * USER
 * ExchangerPoint Crypto Exchange Plateform - USER Specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.user;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdatePinRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-01T06:52:50.420Z")
public class UpdatePinRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("pin")
  private String pin = null;

  public UpdatePinRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

  
  @SerializedName("verificationCode")
  private String verificationCode = null;
  
   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  
  public UpdatePinRequest pin(String newpin) {
    this.pin = newpin;
    return this;
  }
  

  public UpdatePinRequest verificationCode(String verificationCode) {
	    this.verificationCode = verificationCode;
	    return this;
	  }

   /**
   * User new pin
   * @return pin
  **/
  @ApiModelProperty(required = true, value = "User new pin")
  public String getPin() {
    return pin;
  }

  public void setPin(String pin) {
    this.pin = pin;
  }


  /**
   * Email Verification Code
   * @return emailVerificationCode
  **/
  @ApiModelProperty(required = true, value = "Email Verification Code")
  public String getVerificationCode() {
    return verificationCode;
  }

  public void setVerificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePinRequest updatePinRequest = (UpdatePinRequest) o;
    return Objects.equals(this.userName, updatePinRequest.userName) &&
    		Objects.equals(this.verificationCode, updatePinRequest.verificationCode) &&
            Objects.equals(this.pin, updatePinRequest.pin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, pin, verificationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePinRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

