/*
 * USER
 * ExchangerPoint Crypto Exchange Plateform - USER Specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.user;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PasswordResetRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-01T06:52:50.420Z")
public class UpdateEmailRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("email")
  private String email = null;
  
  @SerializedName("pin")
  private String pin = null;
  
  @SerializedName("verificationCode")
  private String verificationCode = null;

  public UpdateEmailRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UpdateEmailRequest pin(String pin) {
	    this.pin = pin;
	    return this;
	  }
  

  
  public UpdateEmailRequest email(String email) {
    this.email = email;
    return this;
  }
  
  
  public UpdateEmailRequest verificationCode(String verificationCode) {
	    this.verificationCode = verificationCode;
	    return this;
	  }

  /**
   * User pin
   * @return pin
  **/
  @ApiModelProperty(required = true, value = "User pin")
  public String getPin() {
    return pin;
  }
  
   /**
   * User new email
   * @return email
  **/
  @ApiModelProperty(required = true, value = "User new email")
  public String getEmail() {
    return email;
  }

  
  public void setPin(String pin) {
	    this.pin = pin;
	  }

  public void setEmail(String email) {
    this.email = email;
  }

  
  /**
   * Email Verification Code
   * @return emailVerificationCode
  **/
  @ApiModelProperty(required = true, value = "Email Verification Code")
  public String getVerificationCode() {
    return verificationCode;
  }

  public void setVerificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEmailRequest updateEmailRequest = (UpdateEmailRequest) o;
    return Objects.equals(this.userName, updateEmailRequest.userName) &&
    		Objects.equals(this.verificationCode, updateEmailRequest.verificationCode) &&
    		Objects.equals(this.pin, updateEmailRequest.pin) &&
        Objects.equals(this.email, updateEmailRequest.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, email, pin, verificationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEmailRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

