/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.application;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PaymentMethodResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-22T11:13:00.539Z")
public class PaymentMethodResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("depositFees")
  private String depositFees = null;

  @SerializedName("withdrawFees")
  private String withdrawFees = null;

  @SerializedName("minimumAmount")
  private String minimumAmount = null;

  @SerializedName("idverification")
  private String idverification = null;

  @SerializedName("addressVerification")
  private String addressVerification = null;

  @SerializedName("cardVerification")
  private String cardVerification = null;

  public PaymentMethodResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PaymentMethodResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public PaymentMethodResponse depositFees(String depositFees) {
    this.depositFees = depositFees;
    return this;
  }

   /**
   * Get depositFees
   * @return depositFees
  **/
  @ApiModelProperty(value = "")
  public String getDepositFees() {
    return depositFees;
  }

  public void setDepositFees(String depositFees) {
    this.depositFees = depositFees;
  }

  public PaymentMethodResponse withdrawFees(String withdrawFees) {
    this.withdrawFees = withdrawFees;
    return this;
  }

   /**
   * Get withdrawFees
   * @return withdrawFees
  **/
  @ApiModelProperty(value = "")
  public String getWithdrawFees() {
    return withdrawFees;
  }

  public void setWithdrawFees(String withdrawFees) {
    this.withdrawFees = withdrawFees;
  }

  public PaymentMethodResponse minimumAmount(String minimumAmount) {
    this.minimumAmount = minimumAmount;
    return this;
  }

   /**
   * Get minimumAmount
   * @return minimumAmount
  **/
  @ApiModelProperty(value = "")
  public String getMinimumAmount() {
    return minimumAmount;
  }

  public void setMinimumAmount(String minimumAmount) {
    this.minimumAmount = minimumAmount;
  }

  public PaymentMethodResponse idverification(String idverification) {
    this.idverification = idverification;
    return this;
  }

   /**
   * Get idverification
   * @return idverification
  **/
  @ApiModelProperty(value = "")
  public String getIdverification() {
    return idverification;
  }

  public void setIdverification(String idverification) {
    this.idverification = idverification;
  }

  public PaymentMethodResponse addressVerification(String addressVerification) {
    this.addressVerification = addressVerification;
    return this;
  }

   /**
   * Get addressVerification
   * @return addressVerification
  **/
  @ApiModelProperty(value = "")
  public String getAddressVerification() {
    return addressVerification;
  }

  public void setAddressVerification(String addressVerification) {
    this.addressVerification = addressVerification;
  }

  public PaymentMethodResponse cardVerification(String cardVerification) {
    this.cardVerification = cardVerification;
    return this;
  }

   /**
   * Get cardVerification
   * @return cardVerification
  **/
  @ApiModelProperty(value = "")
  public String getCardVerification() {
    return cardVerification;
  }

  public void setCardVerification(String cardVerification) {
    this.cardVerification = cardVerification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodResponse paymentMethodResponse = (PaymentMethodResponse) o;
    return Objects.equals(this.name, paymentMethodResponse.name) &&
        Objects.equals(this.currency, paymentMethodResponse.currency) &&
        Objects.equals(this.depositFees, paymentMethodResponse.depositFees) &&
        Objects.equals(this.withdrawFees, paymentMethodResponse.withdrawFees) &&
        Objects.equals(this.minimumAmount, paymentMethodResponse.minimumAmount) &&
        Objects.equals(this.idverification, paymentMethodResponse.idverification) &&
        Objects.equals(this.addressVerification, paymentMethodResponse.addressVerification) &&
        Objects.equals(this.cardVerification, paymentMethodResponse.cardVerification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, currency, depositFees, withdrawFees, minimumAmount, idverification, addressVerification, cardVerification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    depositFees: ").append(toIndentedString(depositFees)).append("\n");
    sb.append("    withdrawFees: ").append(toIndentedString(withdrawFees)).append("\n");
    sb.append("    minimumAmount: ").append(toIndentedString(minimumAmount)).append("\n");
    sb.append("    idverification: ").append(toIndentedString(idverification)).append("\n");
    sb.append("    addressVerification: ").append(toIndentedString(addressVerification)).append("\n");
    sb.append("    cardVerification: ").append(toIndentedString(cardVerification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

