/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.application;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SupportedCurrencyResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-17T12:29:18.763Z")
public class SupportedCurrencyResponse {
  @SerializedName("currencies")
  private List<CurrencyResponse> currencies = null;

  public SupportedCurrencyResponse currencies(List<CurrencyResponse> currencies) {
    this.currencies = currencies;
    return this;
  }

  public SupportedCurrencyResponse addCurrenciesItem(CurrencyResponse currenciesItem) {
    if (this.currencies == null) {
      this.currencies = new ArrayList<CurrencyResponse>();
    }
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * Get currencies
   * @return currencies
  **/
  @ApiModelProperty(value = "")
  public List<CurrencyResponse> getCurrencies() {
    return currencies;
  }

  public void setCurrencies(List<CurrencyResponse> currencies) {
    this.currencies = currencies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportedCurrencyResponse supportedCurrencyResponse = (SupportedCurrencyResponse) o;
    return Objects.equals(this.currencies, supportedCurrencyResponse.currencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportedCurrencyResponse {\n");
    
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

