swagger: '2.0'
info:
  description: ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
  version: "1.0.0"
  title: "ExchangerPoint"
  termsOfService: "http://exchangerpoint.com/terms/"
  contact:
    email: "support@exchangerpoint.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "exchangerpoint.com"
basePath: "/api/v1"
paths:
  /app/currency/:  
    get:
      tags:
        - wallet
      summary: Get all supported currencies in ExchangerPoint platform
      description: Get all supported currencies
      operationId: getWalletCurrencies
      parameters:
        - $ref: '#/parameters/acceptParam'
        - $ref: '#/parameters/userAgentParam'
        - $ref: '#/parameters/acceptEncodingParam'
        - $ref: '#/parameters/cookieParam'
        - $ref: '#/parameters/xRequestIdParam'
      responses:
        '200':
          description: List of supported currencies
          schema:
            $ref: '#/definitions/SupportedCurrencyResponse'
        '400':
          description: |
            ** Error codes: **
            * 1000 - Invalid login/expired session
            * 1006 - User not logged in
            * 1020 - Session timed out
            * 4003 - Access Denied
            * 4000 - Bad request
            * 5000 - Internal Server Error
          schema:
            $ref: '#/definitions/RestError'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/RestError'   

  /app/paymentmethods/:  
    get:
      tags:
        - wallet
      summary: Get all supported payment methods in ExchangerPoint platform
      description: Get all supported payment methods
      operationId: getPaymentMethods
      parameters:
        - $ref: '#/parameters/acceptParam'
        - $ref: '#/parameters/userAgentParam'
        - $ref: '#/parameters/acceptEncodingParam'
        - $ref: '#/parameters/cookieParam'
        - $ref: '#/parameters/xRequestIdParam'
      responses:
        '200':
          description: List of supported payment methods
          schema:
            $ref: '#/definitions/PaymentMethodsResponse'
        '400':
          description: |
            ** Error codes: **
            * 1000 - Invalid login/expired session
            * 1006 - User not logged in
            * 1020 - Session timed out
            * 4003 - Access Denied
            * 4000 - Bad request
            * 5000 - Internal Server Error
          schema:
            $ref: '#/definitions/RestError'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/RestError'
     
parameters:
  acceptParam:
   name: Accept
   in: header
   required: true
   type: string
  userAgentParam:
   name: User-Agent
   in: header
   required: true
   type: string
  acceptEncodingParam:
   name: Accept-Encoding
   in: header
   required: false
   type: string
  xRequestIdParam:
   name: X-Request-Id
   in: header
   required: true
   type: string
  cookieParam:
   name: Cookie
   in: header
   required: true
   type: string
  sessionId:
   name: SessionId
   in: header
   required: true
   type: string
  apiKey:
   name: SessionId
   in: header
   required: true
   type: string
definitions:         
  

  CurrencyResponse:
    properties:
     currency:
       type: string
  
  SupportedCurrencyResponse:
    properties:
      currencies:
        type: array
        items:
          $ref: '#/definitions/CurrencyResponse'
          
  PaymentMethodsResponse:
    properties:
      paymentMethods:
        type: array
        items:
          $ref: '#/definitions/PaymentMethodResponse'        
  
  PaymentMethodResponse:
    properties:
     name:
       type: string
     currency:
       type: string
     depositFees:
       type: string 
     withdrawFees:
       type: string       
     minimumAmount:
       type: string
     idverification:
       type: string
     addressVerification:
       type: string
     cardVerification:
       type: string
       
  RestError:
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
    required:
      - errorCode
      - errorMessage