/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.wallet;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddBankAccountRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-23T10:29:16.975Z")
public class AddBankAccountRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("accountHolderName")
  private String accountHolderName = null;

  @SerializedName("ifscCode")
  private String ifscCode = null;

  public AddBankAccountRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public AddBankAccountRequest accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @ApiModelProperty(value = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AddBankAccountRequest accountHolderName(String accountHolderName) {
    this.accountHolderName = accountHolderName;
    return this;
  }

   /**
   * Get accountHolderName
   * @return accountHolderName
  **/
  @ApiModelProperty(value = "")
  public String getAccountHolderName() {
    return accountHolderName;
  }

  public void setAccountHolderName(String accountHolderName) {
    this.accountHolderName = accountHolderName;
  }

  public AddBankAccountRequest ifscCode(String ifscCode) {
    this.ifscCode = ifscCode;
    return this;
  }

   /**
   * Get ifscCode
   * @return ifscCode
  **/
  @ApiModelProperty(value = "")
  public String getIfscCode() {
    return ifscCode;
  }

  public void setIfscCode(String ifscCode) {
    this.ifscCode = ifscCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddBankAccountRequest addBankAccountRequest = (AddBankAccountRequest) o;
    return Objects.equals(this.userName, addBankAccountRequest.userName) &&
        Objects.equals(this.accountNumber, addBankAccountRequest.accountNumber) &&
        Objects.equals(this.accountHolderName, addBankAccountRequest.accountHolderName) &&
        Objects.equals(this.ifscCode, addBankAccountRequest.ifscCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, accountNumber, accountHolderName, ifscCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddBankAccountRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountHolderName: ").append(toIndentedString(accountHolderName)).append("\n");
    sb.append("    ifscCode: ").append(toIndentedString(ifscCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

