/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.wallet;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * BankAccountsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-23T10:29:16.975Z")
public class BankAccountsResponse {
  @SerializedName("bankDetails")
  private List<BankAccountResponse> bankDetails = null;

  public BankAccountsResponse bankDetails(List<BankAccountResponse> bankDetails) {
    this.bankDetails = bankDetails;
    return this;
  }

  public BankAccountsResponse addBankDetailsItem(BankAccountResponse bankDetailsItem) {
    if (this.bankDetails == null) {
      this.bankDetails = new ArrayList<BankAccountResponse>();
    }
    this.bankDetails.add(bankDetailsItem);
    return this;
  }

   /**
   * Get bankDetails
   * @return bankDetails
  **/
  @ApiModelProperty(value = "")
  public List<BankAccountResponse> getBankDetails() {
    return bankDetails;
  }

  public void setBankDetails(List<BankAccountResponse> bankDetails) {
    this.bankDetails = bankDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountsResponse bankAccountsResponse = (BankAccountsResponse) o;
    return Objects.equals(this.bankDetails, bankAccountsResponse.bankDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountsResponse {\n");
    
    sb.append("    bankDetails: ").append(toIndentedString(bankDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

