/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.wallet;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdateWalletRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-23T10:29:16.975Z")
public class UpdateWalletRequest {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("autoConvert")
  private Boolean autoConvert = null;

  public UpdateWalletRequest userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Unique id for user identification
   * @return userName
  **/
  @ApiModelProperty(required = true, value = "Unique id for user identification")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UpdateWalletRequest currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Supported values - USD, GBP, EUR, INR, CAD, AUD 
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "Supported values - USD, GBP, EUR, INR, CAD, AUD ")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public UpdateWalletRequest autoConvert(Boolean autoConvert) {
    this.autoConvert = autoConvert;
    return this;
  }

   /**
   * Get autoConvert
   * @return autoConvert
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutoConvert() {
    return autoConvert;
  }

  public void setAutoConvert(Boolean autoConvert) {
    this.autoConvert = autoConvert;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateWalletRequest updateWalletRequest = (UpdateWalletRequest) o;
    return Objects.equals(this.userName, updateWalletRequest.userName) &&
        Objects.equals(this.currency, updateWalletRequest.currency) &&
        Objects.equals(this.autoConvert, updateWalletRequest.autoConvert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, currency, autoConvert);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateWalletRequest {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    autoConvert: ").append(toIndentedString(autoConvert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

