/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.wallet;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WalletResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-17T12:29:18.763Z")
public class WalletResponse {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("currencySymbol")
  private String currencySymbol = null;

  @SerializedName("autoConvert")
  private String autoConvert = null;

  @SerializedName("availableBalance")
  private String availableBalance = null;

  @SerializedName("pendingBalance")
  private String pendingBalance = null;

  @SerializedName("reserveBalance")
  private String reserveBalance = null;

  @SerializedName("totalBalance")
  private String totalBalance = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("modifiedDate")
  private String modifiedDate = null;

  @SerializedName("walletStatus")
  private String walletStatus = null;

  public WalletResponse userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public WalletResponse currencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
    return this;
  }

   /**
   * Get currencySymbol
   * @return currencySymbol
  **/
  @ApiModelProperty(value = "")
  public String getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public WalletResponse autoConvert(String autoConvert) {
    this.autoConvert = autoConvert;
    return this;
  }

   /**
   * Get autoConvert
   * @return autoConvert
  **/
  @ApiModelProperty(value = "")
  public String getAutoConvert() {
    return autoConvert;
  }

  public void setAutoConvert(String autoConvert) {
    this.autoConvert = autoConvert;
  }

  public WalletResponse availableBalance(String availableBalance) {
    this.availableBalance = availableBalance;
    return this;
  }

   /**
   * Get availableBalance
   * @return availableBalance
  **/
  @ApiModelProperty(value = "")
  public String getAvailableBalance() {
    return availableBalance;
  }

  public void setAvailableBalance(String availableBalance) {
    this.availableBalance = availableBalance;
  }

  public WalletResponse pendingBalance(String pendingBalance) {
    this.pendingBalance = pendingBalance;
    return this;
  }

   /**
   * Get pendingBalance
   * @return pendingBalance
  **/
  @ApiModelProperty(value = "")
  public String getPendingBalance() {
    return pendingBalance;
  }

  public void setPendingBalance(String pendingBalance) {
    this.pendingBalance = pendingBalance;
  }

  public WalletResponse reserveBalance(String reserveBalance) {
    this.reserveBalance = reserveBalance;
    return this;
  }

   /**
   * Get reserveBalance
   * @return reserveBalance
  **/
  @ApiModelProperty(value = "")
  public String getReserveBalance() {
    return reserveBalance;
  }

  public void setReserveBalance(String reserveBalance) {
    this.reserveBalance = reserveBalance;
  }

  public WalletResponse totalBalance(String totalBalance) {
    this.totalBalance = totalBalance;
    return this;
  }

   /**
   * Get totalBalance
   * @return totalBalance
  **/
  @ApiModelProperty(value = "")
  public String getTotalBalance() {
    return totalBalance;
  }

  public void setTotalBalance(String totalBalance) {
    this.totalBalance = totalBalance;
  }

  public WalletResponse createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public WalletResponse modifiedDate(String modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Get modifiedDate
   * @return modifiedDate
  **/
  @ApiModelProperty(value = "")
  public String getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(String modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public WalletResponse walletStatus(String walletStatus) {
    this.walletStatus = walletStatus;
    return this;
  }

   /**
   * Get walletStatus
   * @return walletStatus
  **/
  @ApiModelProperty(value = "")
  public String getWalletStatus() {
    return walletStatus;
  }

  public void setWalletStatus(String walletStatus) {
    this.walletStatus = walletStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletResponse walletResponse = (WalletResponse) o;
    return Objects.equals(this.userName, walletResponse.userName) &&
        Objects.equals(this.currencySymbol, walletResponse.currencySymbol) &&
        Objects.equals(this.autoConvert, walletResponse.autoConvert) &&
        Objects.equals(this.availableBalance, walletResponse.availableBalance) &&
        Objects.equals(this.pendingBalance, walletResponse.pendingBalance) &&
        Objects.equals(this.reserveBalance, walletResponse.reserveBalance) &&
        Objects.equals(this.totalBalance, walletResponse.totalBalance) &&
        Objects.equals(this.createdDate, walletResponse.createdDate) &&
        Objects.equals(this.modifiedDate, walletResponse.modifiedDate) &&
        Objects.equals(this.walletStatus, walletResponse.walletStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, currencySymbol, autoConvert, availableBalance, pendingBalance, reserveBalance, totalBalance, createdDate, modifiedDate, walletStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletResponse {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    currencySymbol: ").append(toIndentedString(currencySymbol)).append("\n");
    sb.append("    autoConvert: ").append(toIndentedString(autoConvert)).append("\n");
    sb.append("    availableBalance: ").append(toIndentedString(availableBalance)).append("\n");
    sb.append("    pendingBalance: ").append(toIndentedString(pendingBalance)).append("\n");
    sb.append("    reserveBalance: ").append(toIndentedString(reserveBalance)).append("\n");
    sb.append("    totalBalance: ").append(toIndentedString(totalBalance)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    walletStatus: ").append(toIndentedString(walletStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

