/*
 * ExchangerPoint
 * ExchangerPoint Crypto Exchange Plateform - API endpoint Specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exchangerpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.exchangerpoint.restspec.dto.wallet;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WalletsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-17T12:29:18.763Z")
public class WalletsResponse {
  @SerializedName("wallets")
  private List<WalletResponse> wallets = null;

  public WalletsResponse wallets(List<WalletResponse> wallets) {
    this.wallets = wallets;
    return this;
  }

  public WalletsResponse addWalletsItem(WalletResponse walletItem) {
    if (this.wallets == null) {
      this.wallets = new ArrayList<WalletResponse>();
    }
    this.wallets.add(walletItem);
    return this;
  }

   /**
   * Get wallets
   * @return wallets
  **/
  @ApiModelProperty(value = "")
  public List<WalletResponse> getWallets() {
    return wallets;
  }

  public void setWallets(List<WalletResponse> wallets) {
    this.wallets = wallets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletsResponse walletsResponse = (WalletsResponse) o;
    return Objects.equals(this.wallets, walletsResponse.wallets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wallets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletsResponse {\n");
    
    sb.append("    wallets: ").append(toIndentedString(wallets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

